server:
  port: 9007
  
spring:
  application:
    name: order-service  
  datasource:
    url: jdbc:mysql://localhost:3306/note
    username: root
    password: Vishnu@139
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
    client:
      register-with-eureka: true
    fetch-registry: true
 