server:
  port: 8761

spring:
  application:
    name: eureka-server

#to make application as eureka server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false          